# Set environment variable LIBMESH_ROOT or execute scons like that: scons LIBMESH_ROOT=$HOME/software/libmesh scons  

import os

vars = Variables(None, ARGUMENTS)
env = Environment(variables = vars, ENV = os.environ)
conf = Configure(env)

libmeshRoot = os.getenv('LIBMESH_ROOT')
preciceRoot = os.getenv('PRECICE_ROOT')

env.Append(CPPPATH = [os.path.join(libmeshRoot, 'include'),
                      "/usr/include/vtk-5.8",
		      os.path.join(preciceRoot, 'src')])
env.Append(LIBPATH = [os.path.join(libmeshRoot, ".libs"),
                      os.path.join(preciceRoot, "build/debug")])

conf.CheckLib("mesh_opt")

env["CXX"] = 'mpicxx'
env.Append(CCFLAGS = ["-g3", "-O0", "-Wall", "-std=c++11", '-fopenmp'])

env.Append(LINKFLAGS = ['-Wl,-rpath,' + os.path.join(libmeshRoot, "lib")])

env.Program('fem-shell-precice', ['fem_shell_precice.cpp'])
